cris.datasource.url=
cris.datasource.username=
cris.datasource.password=
cris.datasource.driverClassName=org.postgresql.Driver

cris.datasource.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect