# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test openaire-cris-validator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout the OpenAIRE Guidelines for CRIS Managers repo
      uses: actions/checkout@v4
      with:
        repository: openaire/guidelines-cris-managers
        path: guidelines-cris-managers
        ref: main
    - name: Move the OpenAIRE Guidelines for CRIS Managers repo to the expected location
      run: mv guidelines-cris-managers ..
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package -Dmaven.javadoc.skip=true -B -V
    - name: Run the validator on the example files
      run: java -jar target/openaire-cris-validator-*-jar-with-dependencies.jar file:samples/
